### ISSUE TITLE
Use Open API instead.

### ISSUE THREAD

**Issue by aaroncrespo** [microsoft/asconnect#7]
`asconnect` has a full OpenAPI spec at: https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip

Instead of re-defining the schema and endpoints based of the documentation. An OpenAPI client generator is probably safer/faster.

**Comment by dalemyers** [comment]
There's a few reasons this was created instead of using the OpenAPI spec:

1. At the time, the spec had a bunch of errors and I couldn't find a generator that would actually generate any code. I̶t̶ ̶s̶e̶e̶m̶s̶ ̶t̶h̶e̶r̶e̶ ̶a̶r̶e̶ ̶f̶e̶w̶e̶r̶ ̶e̶r̶r̶o̶r̶s̶ ̶n̶o̶w̶,̶ ̶b̶u̶t̶ ̶I̶ ̶d̶o̶n̶'̶t̶ ̶k̶n̶o̶w̶ ̶i̶f̶ ̶c̶o̶d̶e̶ ̶c̶a̶n̶ ̶b̶e̶ ̶g̶e̶n̶e̶r̶a̶t̶e̶d̶.̶  I just tried and it _does_ generate now. 
2. The generated version doesn't have types.
3. It's not easy to add convenience methods which can do multiple things without compromising the ability to re-generate in the future. 
4. There's basically no control over retry logic, etc. 
5. The Python code for Swagger generated libraries is pretty awful (there are alternatives, but I doubt they'll be much better). When combined with APIs not named very well you get things like this:

```python
    def app_store_versions_app_store_version_phased_release_get_to_one_related_with_http_info(self, id, **kwargs):  # noqa: E501
        """app_store_versions_app_store_version_phased_release_get_to_one_related  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.app_store_versions_app_store_version_phased_release_get_to_one_related_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: the id of the requested resource (required)
        :param list[str] fields_app_store_version_phased_releases: the fields to include for returned resources of type appStoreVersionPhasedReleases
        :return: AppStoreVersionPhasedReleaseResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        [snipped]

```

It's really not clear what that API is from the name `app_store_versions_app_store_version_phased_release_get_to_one_related_with_http_info`, what the arguments are (it's in the doc comment, but you can see that those are actually out of order, so if you followed them you'd end up doing the wrong thing), etc. 

Let's compare it to yours:

```python
def get_phased_release(
        self,
        *,
        version_id: str,
    ) -> Optional[AppStoreVersionPhasedRelease]:
        """Get the phased release of given app version
        :param version_id: The version ID to query for phased releases
        :returns: An AppStoreVersionPhasedRelease if found, None otherwise
        """
        url = self.http_client.generate_url(
            f"appStoreVersions/{version_id}/appStoreVersionPhasedRelease"
        )

        return next_or_none(self.http_client.get(url=url, data_type=AppStoreVersionPhasedRelease))
```

I know which one I'd rather use.
